#!/bin/bash

set -e
set -u

DIRECTORY=$1

mamba install \
    dicomifier nibabel numpy scipy spire-pipeline \
    make sphinx furo

make -C docs/ html

mkdir "$DIRECTORY"
cp -a docs/_build/html/* "$DIRECTORY/"
