name: Deploy to GitHub pages

on:
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      PYTHON: python
    
    defaults:
      run:
        shell: bash -el {0}
    
    steps:
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
      
      - name: Checkout latest revision
        uses: actions/checkout@v2
      
      - name: Install requirements
        run: ./.ci/build
      
      - name: Build package
        run: ./.ci/build
      
      - name: Build doc
        run: ./.ci/pages public
      
      - name: Skip Jekyll processing when deploying
        run: touch public/.nojekyll
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          clean: false
          single-commit: true
          # NOTE: commits through default token do not trigger deployment
          ssh-key: ${{ secrets.PAGES_DEPLOY_KEY }}
